source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]


#--------------------------------
# http://stackoverflow.com/questions/5500271/connect-to-remote-host-from-aptana-studio-3-terminal ssh -l <username> 192.168.0.100

#http://www.morshed-alam.com/2012/04/how-to-rename-rails-3-application.html

# http://wiki.dreamhost.com/Ruby_on_Rails
# bu linke bakarak hostingi fastcgiya gore ayarla.

# su sayfaya gore dreamhostda islem yaptim. sadece rubygems tgz dosyasinin versiyon numarasini rename ettim ve wget ile degil winscp ile kopyaladim.
# http://blog.joeygeiger.com/2010/05/17/i-beat-dreamhost-how-to-really-get-rails-3-bundler-and-dreamhost-working/

#gem "bcrypt-ruby", :require => "bcrypt" #turker bu satırı ekledikten sonra bundle install komutunu çalıştır http://railscasts.com/episodes/250-authentication-from-scratch http://yorickpeterse.com/articles/use-bcrypt-fool/

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end



=begin
gem 'rake', '0.8.7'
gem 'abstract', '1.0.0'
gem 'activesupport', '3.0.3'
gem 'builder', '2.1.2'
gem 'i18n', '0.4.2'
gem 'activemodel', '3.0.3'
gem 'erubis', '2.6.6'
gem 'rack', '1.2.1'
gem 'rack-mount', '0.6.13'
gem 'rack-test', '0.5.6'
gem 'tzinfo', '0.3.23'
gem 'actionpack', '3.0.3'
gem 'mime-types', '1.16'
gem 'polyglot', '0.3.1'
gem 'treetop', '1.4.9'
gem 'mail', '2.2.15'
gem 'actionmailer', '3.0.3'
gem 'arel', '2.0.4'
gem 'activerecord', '3.0.3'
gem 'activeresource', '3.0.3'
gem 'bundler', '1.0.7'
gem 'thor', '0.14.6'
gem 'railties', '3.0.3'
gem 'rails', '3.0.3'
#gem 'sqlite3-ruby', '1.2.1'
=end














=begin
http://blog.joeygeiger.com/2010/05/17/i-beat-dreamhost-how-to-really-get-rails-3-bundler-and-dreamhost-working/
http://wiki.dreamhost.com/Bundler#Compatibility_Notes
http://wiki.dreamhost.com/Bundler
http://railscasts.com/episodes/250-authentication-from-scratch
http://yorickpeterse.com/articles/use-bcrypt-fool/
Try running `bundle install`.
[fitzpatrick]$ bundle install
Fetching source index for http://rubygems.org/
Using rake (0.8.7)
Using abstract (1.0.0)
Using activesupport (3.0.3)
Using builder (2.1.2)
Using i18n (0.4.2)
Using activemodel (3.0.3)
Using erubis (2.6.6)
Using rack (1.2.1)
Using rack-mount (0.6.13)
Using rack-test (0.5.6)
Using tzinfo (0.3.23)
Using actionpack (3.0.3)
Using mime-types (1.16)
Using polyglot (0.3.1)
Using treetop (1.4.9)
Using mail (2.2.15)
Using actionmailer (3.0.3)
Using arel (2.0.4)
Using activerecord (3.0.3)
Using activeresource (3.0.3)
Installing bcrypt-ruby (3.0.1) with native extensions
Using bundler (1.0.7)
Using thor (0.14.6)
Using railties (3.0.3)
Using rails (3.0.3)
Using sqlite3-ruby (1.2.1)
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.


[fitzpatrick]$ bundle show bcrypt-ruby
/home/toplumektup/.gems/gems/bcrypt-ruby-3.0.1


=end

=begin
 gem list

*** LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.3, 2.3.8, 2.3.5, 2.3.4, 2.3.3, 2.2.2, 2.1.2, 2.1.1, 2.1.0, 2.0.5, 2.0.2)
actionpack (3.0.3, 2.3.8, 2.3.5, 2.3.4, 2.3.3, 2.2.2, 2.1.2, 2.1.1, 2.1.0, 2.0.5, 2.0.2)
actionwebservice (1.2.6, 1.2.3)
activemodel (3.0.3)
activerecord (3.0.3, 2.3.8, 2.3.5, 2.3.4, 2.3.3, 2.2.2, 2.1.2, 2.1.1, 2.1.0, 2.0.5, 2.0.2)
activeresource (3.0.3, 2.3.8, 2.3.5, 2.3.4, 2.3.3, 2.2.2, 2.1.2, 2.1.1, 2.1.0, 2.0.5, 2.0.2)
activesupport (3.0.3, 2.3.8, 2.3.5, 2.3.4, 2.3.3, 2.2.2, 2.1.2, 2.1.1, 2.1.0, 2.0.5, 2.0.2)
acts_as_taggable (2.0.2, 1.0.4)
ajax_scaffold_generator (3.1.11, 2.2.1)
archive-tar-minitar (0.5.2, 0.5.1)
arel (2.0.4)
auth_generator (2.0.1, 1.5.3)
bcrypt-ruby (3.0.1)
Bloglines4R (0.1.0)
BlueCloth (1.0.0)
builder (2.1.2, 2.0.0)
bundler (1.0.7)
bunny (0.6.0)
camping (1.5.180, 1.5)
capistrano (2.5.1, 2.1.0, 1.4.1)
cgi_multipart_eof_fix (2.5.0)
classifier (1.3.1)
cmdparse (2.0.2, 2.0.0)
curb (0.1.4)
daemons (1.0.10, 1.0.9)
dbd-mysql (0.4.3)
dbi (0.4.3)
deprecated (2.0.1)
erubis (2.6.6)
eventmachine (0.12.10, 0.12.8)
facets (2.2.1, 1.8.54)
fastthread (1.0.7, 1.0.1)
feedtools (0.2.29, 0.2.28)
ferret (0.11.6, 0.11.4)
flickr (1.0.2)
gd2 (1.1.1, 1.1)
gem_plugin (0.2.3)
gen (0.41.0)
geoip (0.6.1)
gettext (1.90.0)
glue (0.41.0)
gnuplot (2.2)
gravtastic (2.0.0)
gruff (0.3.1)
haml (2.0.3)
highline (1.6.2)
hoe (2.7.0)
hpricot (0.6)
htmltools (1.10)
i18n (0.4.2, 0.4.1)
json (1.5.1)
localization_generator (1.0.8)
login_generator (1.2.2)
logstash-lite (0.2.20110206003603)
madeleine (0.7.3)
mail (2.2.15)
markaby (0.5)
mechanize (0.7.6)
metaid (1.0)
mime-types (1.16)
mini_magick (1.2.3)
mixlib-authentication (1.1.0)
mixlib-cli (1.1.0)
mixlib-config (1.1.2)
mixlib-log (1.3.0)
moneta (0.6.0)
mongrel (1.1.5, 1.1.4)
mysql (2.7)
needle (1.3.0)
net-scp (1.0.4)
net-sftp (2.0.5, 1.1.1)
net-ssh (2.1.4)
net-ssh-gateway (1.1.0)
net-ssh-multi (1.1, 1.0.1)
nitro (0.41.0)
nokogiri (1.4.4)
og (0.41.0)
ohai (0.6.0)
oniguruma (1.1.0)
packet (0.1.14)
PageTemplate (2.2.0)
ParseTree (2.1.1)
payment (1.0.1)
pdf-writer (1.1.8)
podcast (0.0.4)
polyglot (0.3.1)
rack (1.2.1, 1.1.0, 1.0.1, 1.0.0)
rack-mount (0.6.13)
rack-test (0.5.6)
radiant (0.6.9)
rails (3.0.3, 2.3.8, 2.3.5, 2.3.4, 2.3.3, 2.2.2, 2.1.2, 2.1.1, 2.1.0, 2.0.5, 2.0.2)
railties (3.0.3)
rake (0.8.7)
RedCloth (3.0.4)
rest-client (1.6.3)
rfacebook (0.9.8)
rmagick (1.15.14)
rspec (1.1.3)
ruby-breakpoint (0.5.1)
ruby-debug (0.10.0)
ruby-openid (2.1.7)
ruby-yadis (0.3.4)
ruby_odeum (0.4.1)
rubyforge (2.0.4)
RubyInline (3.6.7)
rubypants (0.2.0)
rubyzip (0.9.1)
ruport (1.6.0)
ruport-util (0.14.0)
ruwiki (0.9.3)
salted_login_generator (2.0.2)
shipping (1.5.1)
SimpleSearch (0.5.0)
sqlite3-ruby (1.2.1)
stemmer (1.0.1)
switchtower (1.0.1)
syntax (1.0.0)
systemu (2.2.0)
tagtools (0.0.3)
thin (1.2.5, 1.2.2)
thor (0.14.6, 0.14.4)
tidy (1.1.2)
treetop (1.4.9)
tzinfo (0.3.23)
unicode (0.1)
uuidtools (1.0.3)
webgen (0.4.7)
wee (0.10.0)
xhtmldiff (1.0.0)
xml-simple (1.0.11)
yajl-ruby (0.8.2)
ym4r (0.6.1)
youtube-g (0.4.9.9)

=end

=begin



RubyGems installed the following executables:
        /home/toplumektup/opt/bin/gem1.8

Ruby Interactive (ri) documentation was installed. ri is kind of like man
pages for ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.







=end

=begin

http://www.morshed-alam.com/2012/04/how-to-rename-rails-3-application.html
 How to rename Rails3 application
A Rails3 application name are using as a Ruby name space for entire application and throughout the project tree as well. So, If anyone later decide to change the project name, then have to replace the name in the following files:
01	Rakefile
02	config.ru
03	config/routes.rb
04	config/application.rb
05	config/environment.rb
06	config/environments/development.rb
07	config/environments/test.rb
08	config/environments/production.rb
09	initializers/secret_token.rb
10	initializers/session_store.rb

You can run following command in your project root, to find out the list of files containing project name(assume you are using linux):
1	grep -Ri 'AppName' * | cut -f1 -d':' | sort | uniq

You can use following gem to rename rails3 application without any hassle:
https://github.com/morshedalam/rename

=end